article/urls.py
from django.urls import path

from . import views

app_name = 'article'

urlpatterns = [
    path('', views.articles, name="articls_list"),
    path('/<str:slug>', views.single_article, name="single_article")
]

home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.home, name='home')
]

project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('about', include('about.urls')),
    path('contact', include('contact.urls')),
    path('article', include('article.urls', namespace='all_articles')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article/models.py
from django.db import models
from datetime import datetime
from django.utils.text import slugify


class Article_Info(models.Model):
    image = models.ImageField(upload_to='article_img')
    title = models.CharField(max_length=100)
    small_description = models.CharField(
        max_length=150, verbose_name='Description')
    owner = models.CharField(max_length=50)
    at_time = models.DateTimeField(default=datetime.now)
    type_section = models.ForeignKey('Section', on_delete=models.CASCADE)
    important_qouts = models.TextField(max_length=5000, null=True, blank=True)
    paragraph1 = models.TextField(max_length=50000)
    paragraph2 = models.TextField(max_length=50000)
    paragraph3 = models.TextField(max_length=50000, null=True, blank=True)
    paragraph4 = models.TextField(max_length=50000, null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(Article_Info, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = ' Add Article'
        ordering = ['title']


class Section(models.Model):
    section = models.CharField(max_length=50)

    def __str__(self):
        return self.section


class Comment(models.Model):
    post = models.ForeignKey(
        Article_Info, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return 'Comment {} by {}'.format(self.body, self.name)

article/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

article/views.py
from django.shortcuts import render, get_object_or_404
from .forms import CommentForm
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.core.paginator import Paginator
from article.models import Article_Info
from .filters import articleFilter

# Create your views here.


def articles(request):
    art_list = Article_Info.objects.all()

    myfilter = articleFilter(request.GET, queryset=art_list)
    art_list = myfilter.qs

    paginator = Paginator(art_list, 8)
    page_num = request.GET.get('page')
    articles = paginator.get_page(page_num)
    context = {
        'count': paginator.count,
        'articles': articles,
        'title': 'Articles',
        'myfilter': myfilter,
    }
    return render(request, "article/article.html", context)


def single_article(request, slug):
    post = get_object_or_404(Article_Info, slug=slug)
    comments = post.comments.filter(active=True)
    new_comment = None

    # Comment posted
    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():

            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()

    context_single = {'art': Article_Info.objects.get(slug=slug),
                      'title': Article_Info.objects.get(slug=slug),
                      'post': post,
                      'comments': comments,
                      'new_comment': new_comment,
                      'comment_form': comment_form}

    return render(request, "article/single_article.html", context_single)

templates/article/article.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1" style="color: red;">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{count}}+ articles Available</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!-- uri_listing_area_start  -->
<div class="uri_listing_area plus_padding">
    <div class="col-lg-9 container">
        <div class="row">
            <div class="col-lg-3">
                <div class="uri_filter white-bg">
                    <div class="form_inner white-bg">
                        <h3>Filter</h3>
                        <form method="GET">
                            {% bootstrap_form myfilter.form %}
                            <input type="submit" value="Search" class="boxed-btn3 w-100 mt-5">
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-9">
                <div class="recent_urilist_wrap">
                    <div class="recent_urilist white-bg ">
                        <div class="row align-items-center">
                            <div class="col-md-6">
                                <h3>All Articles ... </h3>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="uri_lists m-0">
                    <div class="row">
                        {% for article in articles %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_uris white-bg d-flex justify-content-between">
                                    <div class="uris_left d-flex align-items-center">
                                        <div class="thumbb">
                                            <img class='art_img' src="{{article.image.url}}" alt="">
                                        </div>
                                        <div class="uris_conetent">
                                            <a href="{% url 'all_articles:single_article' article.slug %}">
                                                <h3>{{article}}</h3>
                                            </a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> By {{article.owner}}</p>
                                                </div>
                                                &nbsp; &nbsp; &nbsp;
                                                <div class="location">
                                                    <p> {{article.type_section}}</p>
                                                </div>
                                            </div>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p>{{article.small_description}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="uris_right">
                                            <p>Date : {{article.at_time|date:'H:i - d M, Y'}}</p>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}
                    </div>
                    {% if articles.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if articles.has_previous %}
                                            <li><a href="{% url 'all_articles:articls_list' %}?page={{articles.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}
                                        {% for i in articles.paginator.page_range %}
                                            <li><a href="{% url 'all_articles:articls_list' %}?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}
                                        {% if articles.has_next %}
                                            <li><a href="{% url 'all_articles:articls_list' %}?page={{articles.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
</div>
<!-- uri_listing_area_end  -->
{% endblock body %}

templates/article/single_article.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% load static %}
{% block body %}
<!-- bradcam_area  -->
<div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{art.title}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<!--================Article Area =================-->
<section class="blog_area single-post-area section-padding">
    <div class="container">
        <div class="row">
            <div class="col-lg-10 mx-auto posts-list">
                <div class="single-post">
                    <div class="feature-img">
                        <img class="img-fluid" src="{{art.image.url}}" alt="">
                    </div>
                    <div class="blog_details">
                        <h2> ' {{art.small_description}} '</h2>
                        <ul class="blog-info-link mt-3 mb-3">
                            <li> <h4> &nbsp; Section : {{art.type_section}} </h4></a></li>
                        </ul>
                        <p class="excert">
                            {{art.paragraph1}}
                        </p>
                        <p>
                            {{art.paragraph2}}
                        </p>
                        <p>
                            {{art.paragraph3}}
                        </p>
                        <p>
                            {{art.paragraph4}}
                        </p>
                        {% if not art.important_qouts %}
                        {% else %}
                        <div class="quote-wrapper">
                            <div class="quotes">
                                {{art.important_qouts}}
                            </div>
                        </div>
                        {% endif%}
                    </div>
                </div>
                <div class="navigation-top">
                    <div class="col-lg-4 row">
                        <h5> - By {{art.owner}}</h5> 
                    </div>
            </div>
        </div>
    </div>
</section>
<!--================ Article Area end =================-->
<div class="container">
    <div class="row">
        <div class="col-md-8 card mb-4  mt-3 mx-auto">
            <div class="card-body">
                <!-- comments -->
                <h2>{{ comments.count }} comments</h2>

                {% for comment in comments %}
                <div class="comments" style="padding: 10px;">
                    <p class="font-weight-bold">
                        {{ comment.name }}
                        <span class=" text-muted font-weight-normal">
                            {{ comment.created_on }}
                        </span>
                    </p>
                    {{ comment.body | linebreaks }}
                </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-8 card mb-4  mt-3 mx-auto">
            <div class="card-body">
                {% if new_comment %}
                <div class="alert alert-success" role="alert">
                    Your comment is awaiting moderation
                </div>
                {% else %}
                <h3>Leave a comment</h3>
                    <form method="post" style="margin-top: 1.3em;">
                        {% csrf_token %}
                        {% bootstrap_form comment_form %}
                        <button type="submit" class="boxed-btn3 w-100 mt-2">Submit</button>
                    </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock body %}